---
apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9346
---
apiVersion: v1
kind: Service
metadata:
  name: dbservice
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9377
    