apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  restartPolicy: Never
  # volumes are the empty directory, it is directory which is created when the pod is created, and is empties when the pod dies.
  volumes:
  - name: shared-data
    emptyDir: {}

  containers:
  # this section now has 2 main containers, in the single pod.
  - name: nginx-container
    image: nginx
    volumeMounts:
    # volume names shared-data is mounted on the path "/usr/share/nginx/html"
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: alpine-container
    image: alpine
    volumeMounts:
    # shared data volume mount is mounted to the path "/mem-info"
    - name: shared-data
      mountPath: /mem-info
    command: ["/bin/sh","-c"]
    args:
    # this loop is used to append the data we are reading the data entered by the nginx container, into the apline container.
    - while true; do
        date >> /mem-info/index.html ;
        egrep --color 'Mem|Cache|Swap' /proc/meminfo >> /mem-info/index.html ;
        sleep 2;
      done